"""
Vendor / third-party source file classifier.

The mutation and build-fix pipeline should treat bundled libraries as frozen
dependencies: compile and link them, but avoid selecting their functions for
mutation or sending whole files to an LLM fixer.  This module centralizes that
decision so agents do not grow separate hard-coded lists.
"""

from __future__ import annotations

from dataclasses import dataclass
import os
import re
from typing import Iterable, Optional


@dataclass(frozen=True)
class VendorClassification:
    path: str
    score: int
    is_vendor: bool
    reasons: tuple[str, ...]
    size_bytes: int = 0


_EXACT_VENDOR_BASENAMES = frozenset(
    {
        "sqlite3.c",
        "sqlite3.h",
        "sqlite.c",
        "sqlite.h",
        "parson.c",
        "parson.h",
        "cjson.c",
        "cjson.h",
        "json.c",
        "json.h",
        "json.cpp",
        "zip.c",
        "zip.cpp",
        "zip.h",
        "unzip.c",
        "unzip.h",
        "miniz.c",
        "miniz.h",
        "zlib.c",
        "zlib.h",
        "lodepng.c",
        "lodepng.cpp",
        "lodepng.h",
        "stb_image.h",
        "stb_image_write.h",
        "stb_truetype.h",
        "stb_vorbis.c",
        "md5.c",
        "md5.h",
        "sha1.c",
        "sha1.h",
        "sha256.c",
        "sha256.h",
        "aes.c",
        "aes.h",
        "rc4.c",
        "rc4.h",
        "base64.c",
        "base64.h",
        "http_parser.c",
        "http_parser.h",
        "mongoose.c",
        "mongoose.h",
        "tiny-regex-c.c",
        "xxhash.c",
        "xxhash.h",
    }
)

_VENDOR_STEM_MARKERS = (
    "sqlite",
    "parson",
    "cjson",
    "miniz",
    "zlib",
    "lodepng",
    "stb_",
    "xxhash",
    "http_parser",
    "mongoose",
)

_VENDOR_DIR_MARKERS = frozenset(
    {
        "vendor",
        "third_party",
        "third-party",
        "external",
        "extern",
        "deps",
        "dependencies",
        "lib",
        "libs",
        "library",
        "libraries",
    }
)

_CONTENT_MARKERS = (
    "amalgamation",
    "single-file",
    "single file",
    "public domain",
    "generated by",
    "automatically generated",
    "do not edit",
    "sqlite",
    "parson",
    "zlib",
    "miniz",
    "stb_",
    "cjson",
    "lodepng",
)

_SOURCE_EXTS = frozenset({".c", ".cc", ".cpp", ".cxx", ".h", ".hpp", ".hh", ".hxx"})


def _safe_size(path: str) -> int:
    try:
        return os.path.getsize(path)
    except OSError:
        return 0


def _read_probe(path: str, max_bytes: int = 65536) -> str:
    try:
        with open(path, "rb") as fh:
            data = fh.read(max_bytes)
    except OSError:
        return ""
    return data.decode("utf-8", errors="ignore").lower()


def _path_parts(path: str) -> list[str]:
    norm = os.path.normpath(path).lower()
    drive, rest = os.path.splitdrive(norm)
    del drive
    return [p for p in re.split(r"[\\/]+", rest) if p]


def classify_source_file(
    path: str,
    *,
    function_count: Optional[int] = None,
    threshold: int = 3,
    read_content: bool = True,
) -> VendorClassification:
    """Classify a source/header file as project code or frozen vendor code.

    The score intentionally combines weak signals.  A large file alone is not
    enough to freeze it, but a large file with a known library name or
    amalgamation marker is.
    """

    reasons: list[str] = []
    score = 0
    basename = os.path.basename(path).lower()
    stem, ext = os.path.splitext(basename)
    size = _safe_size(path)

    if ext and ext not in _SOURCE_EXTS:
        return VendorClassification(path, 0, False, tuple(), size)

    if basename in _EXACT_VENDOR_BASENAMES:
        score += 3
        reasons.append(f"known_vendor_name:{basename}")
    elif any(stem == marker or stem.startswith(marker) for marker in _VENDOR_STEM_MARKERS):
        score += 2
        reasons.append(f"vendor_name_marker:{stem}")

    parts = _path_parts(path)
    if any(part in _VENDOR_DIR_MARKERS for part in parts):
        score += 2
        reasons.append("vendor_directory")

    if size >= 1_000_000:
        score += 3
        reasons.append(f"very_large:{size}")
    elif size >= 200_000:
        score += 2
        reasons.append(f"large:{size}")
    elif size >= 80_000:
        score += 1
        reasons.append(f"medium_large:{size}")

    if function_count is not None:
        if function_count >= 300:
            score += 2
            reasons.append(f"many_functions:{function_count}")
        elif function_count >= 100:
            score += 1
            reasons.append(f"many_functions:{function_count}")

    if read_content and size:
        probe = _read_probe(path)
        marker_hits = [marker for marker in _CONTENT_MARKERS if marker in probe]
        if marker_hits:
            score += min(2, len(marker_hits))
            reasons.append("content_marker:" + ",".join(marker_hits[:3]))

    return VendorClassification(path, score, score >= threshold, tuple(reasons), size)


def is_vendor_file(path: str, **kwargs) -> bool:
    return classify_source_file(path, **kwargs).is_vendor


def filter_vendor_files(paths: Iterable[str], **kwargs) -> list[str]:
    return [path for path in paths if not is_vendor_file(path, **kwargs)]

